### ISSUE TITLE
[CLI] remote tracking fails at key unlock

### ISSUE THREAD

**Issue by stevewalsh** [keybase/keybase-issues#1368]
Earlier tonight, I got the email to tell me that person X (who I follow on twitter) was now a keybase subscriber, and had proved their twitter account. 

Great! I thought, I do a fair bit with X, I should probably track him on keybase. Logging in from  home to a remote machine that has my private keys and the keybase cli client installed on it, I run the track;

$ keybase track [person X]
info: ...checking identity proofs
[insert public key proof here]
[insert other proofs here]
Is this the Person X you wanted? [y/N] y
Permanently track this user, and write proof to server? [Y/n] y
info: Updated file: /path/to/keybase/session.json

You need a passphrase to unlock the secret key for
user: "Steve Walsh [email@address.com]"
[insert key identifying information here]

.....and that where it stopped. I wasn't given a prompt at the cli to enter the passphrase at, so I had to ctrl-C the tracking and remote in to the machine GUI and do it. I'm assuming this is because I have seahorse on the remote machine, so it normally pops the seahorse-gnome passphrase window up, but perhaps some shell detection might be useful?

Centos 6.6

$ gpg --version
gpg (GnuPG) 2.0.14
libgcrypt 1.4.5
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA
Cipher: 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH, CAMELLIA128, 
        CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

$ keybase version
keybase (keybase.io CLI) v0.7.3
- node.js v0.10.36
- gpg (GnuPG) 2.0.14
- libgcrypt 1.4.5
Identifies as: 'keybase.io node.js client v0.7.3 linux'

thanks!

**Comment by maxtaco** [comment]
Does this help?

https://github.com/keybase/keybase-issues/issues/562

I'll hopefully have some time today to fix this issue.

**Comment by maxtaco** [comment]
Tried a bunch but can't find a good way to get the current TTY in node.  It's quite frustrating.  So I'd try the shell hack suggested in #562.

**Comment by maxtaco** [comment]
Fixed, hopefully once and for all, in v0.7.4

**Comment by lavagetto** [comment]
Just as a FYI, this still fails when in a tmux window. And you thought cli support was simple :P

**Comment by NotTheEconomist** [comment]
Still having this issue on Windows 7.

C:\Users\adsmith>gpg --version
gpg (GnuPG) 2.0.27 (Gpg4win 2.2.4)
libgcrypt 1.6.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: C:/Users/adsmith/AppData/Roaming/gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

C:\Users\adsmith>keybase --version
0.7.7
