### ISSUE TITLE
Keybase account stopped working after update

### ISSUE THREAD

**Issue by pnelsen** [keybase/keybase-issues#1765]
It appears that keybase recommended an update from 0.7.1 (now on 0.8.18), and ever since I get the following error message with pretty much every command:
error: Previous payload hash doesn't match

I attempted to logout/login and I get the error message on logging in.
Attempted to reset and login and I see the error.

See the error on multiple platforms (OSX, ubuntu).  Have not attempted to downgrade

**Comment by maxtaco** [comment]
Can you post a debug output with -d?   Thanks.

**Comment by pnelsen** [comment]
Ugh!  I had to move on so I don't have the issue anymore, but this has evolved into another issue.  Using the web UI I reset everything and tried to regenerate my keys.  After I ran keybase login and keybase gen, it appears that I'm seeing: 
$ keybase gen
Your key passphrase (can be the same as your login passphrase): ************
Repeat to confirm: ************
Generating keys......... Done!
Push your public key to the server? [Y/n] Y
Push your encrypted private key to the server? [Y/n] n
error: You need to delete your active key before uploading a new one (error #908)

After a brief scan of the issues it appears that someone else is also seeing this on 0.8.18.  #1688 
It appears that revoke does nothing and says the following:
$ keybase revoke
error: No local key to revoke!

**Comment by maxtaco** [comment]
I think I fixed a bug in your account, try `keybase gen` again? Thanks for your patience and help.

**Comment by maxtaco** [comment]
@pnelsen I spent some time looking into the original bug, and according to the site, your sigchain looks fine.  Do you have any more debugging input?  The rest of the debug output would be greatly useful.  It should have said what it expected and what it got. Thanks.

**Comment by pnelsen** [comment]
@maxtaco , thanks for the quick response.  I did have a chance to regenerate the key, and it turns out that I'm still seeing the same issue.

/N) y
Patricks-MacBook-Pro:~ patricknelsen$ keybase gen
Your key passphrase (can be the same as your login passphrase): ****************
Repeat to confirm: ****************
Generating keys.
..... Done!
Push your public key to the server? [Y/n] 
info: Updated file: /Users/patricknelsen/.cache/keybase/session.json
Push your encrypted private key to the server? [Y/n] n
info: success!

Patricks-MacBook-Pro:~ patricknelsen$ keybase -d list-sigs
debug: + opening config file: /Users/patricknelsen/.config/keybase/config.json
debug: ++ loading config file /Users/patricknelsen/.config/keybase/config.json
debug: -- loaded config file -> {"user":{"name":"pnelsen","salt":"4e6634f49693975f5985d53b8cf3727a","id":"619e6eddd3df78745ecc4b3755295b19"}}
debug: - opened config file; found=true
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg
debug: - tested GPG command-line client -> null
debug: Setting GPG_TTY=/dev/ttys003
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.8.18
debug: | Platform info: {"versions":{"http_parser":"2.3","node":"0.12.7","v8":"3.28.71.19","uv":"1.6.1","zlib":"1.2.8","modules":"14","openssl":"1.0.1p"},"arch":"x64","platform":"darwin","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls_ocsp":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.8.18","- node.js v0.12.7","- gpg (GnuPG) 1.4.19","- Copyright (C) 2015 Free Software Foundation, Inc.","Identifies as: 'keybase.io node.js client v0.8.18 darwin'"]
debug: - startup message
debug: + opening database file: /Users/patricknelsen/.local/share/keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 0
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /Users/patricknelsen/.cache/keybase/session.json
debug: +++ loading config file /Users/patricknelsen/.cache/keybase/session.json
debug: --- loaded config file -> <redacted>
debug: -- opened config file; found=true
debug: - session::load
debug: + session::check
debug: | calling to sesscheck
debug: ++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: || Adding a custom CA for host api.keybase.io when tls=true
debug: -- request to sesscheck -> null
debug: - session::check
debug: + User::load_me
debug: ++ pnelsen: load user
debug: +++ pnelsen: load user from local storage
debug: ++++ load sig chain from local storage
debug: |||| loading sig chain w/ payload hash 605525686fef18180be692df6106c13dae39abb2799dc9e8bed1e2bb64e9b886
debug: +++++ 619e6eddd3df78745ecc4b3755295b19: load signature chain
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 605525686fef18180be692df6106c13dae39abb2799dc9e8bed1e2bb64e9b886
debug: ||||| -> found link and previous; prev=f1509495f4f1d46e43dcdd341156b975f7ad19aefeb250a80fd2b236c517a891
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link f1509495f4f1d46e43dcdd341156b975f7ad19aefeb250a80fd2b236c517a891
debug: ||||| -> found link and previous; prev=09527db7672bf23a9681ac86c70826cdc01ed1e467252a76ca4bf4ad0964efd7
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 09527db7672bf23a9681ac86c70826cdc01ed1e467252a76ca4bf4ad0964efd7
debug: ||||| -> found link and previous; prev=439cb3f0b4774688deb5db2fe2e92b9f411f1753e131e4e1cfb79abb904dd4b8
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 439cb3f0b4774688deb5db2fe2e92b9f411f1753e131e4e1cfb79abb904dd4b8
debug: ||||| -> found link and previous; prev=bb4b8cd1484f7ed9f45af965b4f27d16602a6768f1a99f60a5a744d0d5da4d6b
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link bb4b8cd1484f7ed9f45af965b4f27d16602a6768f1a99f60a5a744d0d5da4d6b
debug: ||||| -> found link and previous; prev=c3e489b75fa8b188eabd5df420f035865c46fb1dbe0530dcc030852713e5d8e8
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link c3e489b75fa8b188eabd5df420f035865c46fb1dbe0530dcc030852713e5d8e8
debug: ||||| -> found link and previous; prev=ca08223a56cd5127ad5242912954c0b2c9b9345dd2475f09a4c3f9a7fa459e21
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link ca08223a56cd5127ad5242912954c0b2c9b9345dd2475f09a4c3f9a7fa459e21
debug: ||||| -> found link and previous; prev=20639787fa9a049dd51059eb36c58b88181d2c97d856c84e610a98e225609903
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 20639787fa9a049dd51059eb36c58b88181d2c97d856c84e610a98e225609903
debug: ||||| -> found link and previous; prev=479ed752fa2eb513cf59f835b69098e9ed845593a8e96b400baeab20f88e5a76
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 479ed752fa2eb513cf59f835b69098e9ed845593a8e96b400baeab20f88e5a76
debug: ||||| -> found link and previous; prev=8b9f2b83ae4c160c03c5ea39af51b257d5a561f9211cb99bd3aaf0be9638dad9
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 8b9f2b83ae4c160c03c5ea39af51b257d5a561f9211cb99bd3aaf0be9638dad9
debug: ||||| -> found link and previous; prev=24876c04fcbee2543202274c5145354f0b6b34a38e37d27824ab0260f98d419b
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 24876c04fcbee2543202274c5145354f0b6b34a38e37d27824ab0260f98d419b
debug: ||||| -> found link and previous; prev=181bf1660e64f8d0399243b18d2b71209a6f20a093b06527f56417d9499709d1
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 181bf1660e64f8d0399243b18d2b71209a6f20a093b06527f56417d9499709d1
debug: ||||| -> found link and previous; prev=37069f84adfad38043651e257053a83e5e22ae2b5cc06909879507bf74efbc53
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 37069f84adfad38043651e257053a83e5e22ae2b5cc06909879507bf74efbc53
debug: ||||| -> found link and previous; prev=65a62af1247817a88c841f0f45aa86876c0d681cd0d25aec326a86a2d5568412
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 65a62af1247817a88c841f0f45aa86876c0d681cd0d25aec326a86a2d5568412
debug: ||||| -> found link and previous; prev=4be366f49c0dab0d8466c6139af9463fd005140130997dd3da140a995029c582
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 4be366f49c0dab0d8466c6139af9463fd005140130997dd3da140a995029c582
debug: ||||| -> found link and previous; prev=d3920272a9064f50d0d6ec76c4f8f0a921d1bbd40c932cd0478204432a09dbd8
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link d3920272a9064f50d0d6ec76c4f8f0a921d1bbd40c932cd0478204432a09dbd8
debug: ||||| -> found link and previous; prev=788bef4ab571d16accad4ce4c0e615dc627096a8464273559d074de2e77151dd
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 788bef4ab571d16accad4ce4c0e615dc627096a8464273559d074de2e77151dd
debug: ||||| -> found link and previous; prev=18f6757dca80f14a0a215585305277341ffce00ebe835d5701640cdd6a07fc55
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 18f6757dca80f14a0a215585305277341ffce00ebe835d5701640cdd6a07fc55
debug: ||||| -> found link and previous; prev=7ad8a4ff1674d62b1dec55ecb5ba0fde2cfdfb060a0f1bd6562eef3fa6f1533f
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 7ad8a4ff1674d62b1dec55ecb5ba0fde2cfdfb060a0f1bd6562eef3fa6f1533f
debug: ||||| -> found link and previous; prev=7d9be7a8fdf0682780edcde42b0be17d35f000d37903462346541f51c725e115
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link 7d9be7a8fdf0682780edcde42b0be17d35f000d37903462346541f51c725e115
debug: ||||| -> found link and previous; prev=ff7e15625797458ef40006bbfe68ead03ef8b87b3bb35a0a02d22570c15d6de0
debug: ||||| 619e6eddd3df78745ecc4b3755295b19: Loading link ff7e15625797458ef40006bbfe68ead03ef8b87b3bb35a0a02d22570c15d6de0
debug: ||||| -> found link and previous; prev=null
debug: ----- 619e6eddd3df78745ecc4b3755295b19: loaded signature chain
debug: ---- loaded sig chain from local storage
debug: --- pnelsen: loaded user from local storage -> null / [object Object]
debug: +++ pnelsen: load user from server
debug: ++++ merkle find_and_verify: uid undefined, username pnelsen
debug: +++++ request to merkle/path (https://api.keybase.io:443/_/api/1.0/merkle/path.json?uid=&username=pnelsen) (cookie=true)
debug: ||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ----- request to merkle/path -> null
debug: +++++ merkle get_merkle_pgp_key
debug: ||||| Call to gpg: { args: [ '-k', '--with-fingerprint', '--with-colons' ],
debug:   quiet: true,
debug:   no_options: true }
debug: ||||| merkle key already found in keyring
debug: ----- merkle get_merkle_pgp_key
debug: |||| Load key /2A32340CEC8C9492 from master keyring (secret=undefined)
debug: |||| Call to gpg: { args: 
debug:    [ '--export',
debug:      '--export-options',
debug:      'export-local-sigs',
debug:      '-a',
debug:      '2A32340CEC8C9492' ] }
debug: +++++ lookup UID
debug: ++++++ read_uids_from_keys 03E146CDAF8136680AD566912A32340CEC8C9492
debug: |||||| Call to gpg: { args: 
debug:    [ '-k',
debug:      '--with-fingerprint',
debug:      '--with-colons',
debug:      '03E146CDAF8136680AD566912A32340CEC8C9492' ],
debug:   quiet: true,
debug:   no_options: true }
debug: |||||| got: [{"username":"Keybase.io Merkle Signing","comment":"v1","email":"merkle@keybase.io"}]
debug: ------ read_uids_from_key -> null
debug:  - Map 2A32340CEC8C9492 -> [object Object] via gpg
debug: ----- looked up UID
debug: +++++ Rollback check
debug: ||||| DB put value kv:e2:f91353afce0a64f8928ac791ab8504aac7d462a49f28e0709c6089c9efaa101258fac741989434ffe51110a2b96c26df4b8e14aaa7a7e8fc63f7bbf2b40422aa
debug: ||||| DB put lookup: lo:5:latest -> 5ae919e3ef71d7d9814df2bcd5c895b27fbc4cfe5bdb3edbe8143dc06a92488f
debug: ----- Rollback check
debug: +++++ request to user/lookup (https://api.keybase.io:443/_/api/1.0/user/lookup.json?username=pnelsen) (cookie=true)
debug: ||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ----- request to user/lookup -> null
debug: ---- pnelsen: loaded user from server
debug: ++++ updating local user w/ remote
debug: +++++ update sig chain; remote_seqno=21
debug: ----- updated sig chain
debug: ---- finished update
debug: ++++ pnelsen: verifying signatures
debug: +++++ pnelsen: verifying sig
debug: ++++++ libkeybase: replay(username: pnelsen, uid: 619e6eddd3df78745ecc4b3755295b19, eldest: 010138c5315ee1b1aaa68a2fa78044a8eff99a71009ea6ed980d4d91f218f3acb33b0a)
debug: |||||| libkeybase: replaying signature 1: 0be370b0cc53eda2dbfd55e46290672361b51699672bee977d6de7181d589d090f
debug: |||||| libkeybase: chain link parsed, type 'web_service_binding'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 2: a79aa38b0ce74263199e1b62f60d342bf403cdeca19e9ac7b120df52737945d10f
debug: |||||| libkeybase: chain link parsed, type 'web_service_binding'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 3: ae98364138aebf280b57047f57d7c2866530628042515b72957cd163b761ac200f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 4: d2dfff954d31942085b0fdab8595a7da061e11e893d25ee9ec06cace1e16fe080f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 5: 06b6c340ea102f5945337ea759289de50603a9e2ad543237343eb90050de40380f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 6: a8c27c8bfb3c231b065d8193817da7f2359170055a48742e6e62d2e56e7049dc0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 7: a1d6f082e8cae7db1466ef8d0f00faec8d5a278fc87bb7374d399f3a73c363190f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 8: fa0034c804ff5179af9fed5742688939984c7c3fb34c21c193d4942ee99c9af20f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 9: 160e775029754c784246c3b895f255b7f03f2e7fc795d077562aa221ed7703420f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 10: 821f8b8415f4af8035da234abaebe09d4da998602b568399b5594955d261c6e40f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 11: 360f0183aec135fec378c1215a62ae5160b852056e65bdc19a7d04ec2d2ac72d0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 12: 1637eac411128d9c72a8f2aad54224e69b4cce77af9e15b15b039f2b65a4266f0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 13: 3fbe43f1aa6ce59809c1254bc40d8351a2c10937f261a1836eb66bd5186c2b250f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 14: 8cc3a6209d6ce6f68f169e662c150a7ee77687bd81346fe67e248f2f40b469780f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 15: fe784a227da3a8b19b6b01a6dbbe257ed59ff2e73fd3050275479a1eee4d563d0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 16: 3584668f9d1e5737fb095edce5857debd37f0e763c5071f2637e9ea17346641d0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 17: 9a9eb131925e6fef353fab0cf727f36b4ff23647ccbaa09f7c3bed60970cd2be0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 18: 47efdd7ab54c45384c5802d7e2a2e46d6cd2faaaad5da5ac1d19502fda8e8ddb0f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 19: 595a73fc649c2c8ccc1aa79384e0b3e7ab3049d8df838f75ef0edbcb5bbc42990f
debug: |||||| libkeybase: chain link parsed, type 'track'
debug: |||||| libkeybase: link not in the current subchain -- skipping ahead
debug: |||||| libkeybase: replaying signature 20: e256078702afd7a15a24681259935b48342a49840ab6a90291b300961669790f0f
debug: |||||| libkeybase: chain link parsed, type 'track'
error: Previous payload hash doesn't match, expected: 67f63579dcb143cde80af2196037e61b8d5410677939c3635fbf44e34e106d6e got: 09527db7672bf23a9681ac86c70826cdc01ed1e467252a76ca4bf4ad0964efd7

**Comment by maxtaco** [comment]
Thanks @pnelsen. Working on it. I see what's going on, but I need to scramble to fix a few things before I get to your breakage

Thanks for bearing with me.

**Comment by maxtaco** [comment]
Should be fixed in v0.8.19.  Feel free to reopen if not.  Thanks for your help!

**Comment by pnelsen** [comment]
Thanks, I am able to login using 0.8.19.  However, when I was making changes, I generated a new private key.  I haven't really had time to look at the internals of keybase, so this might be a dumb question.  I noticed that it shows that I'm still tracking people, but they don't show up in sigs.  Do I need to manually remove and re-add each user?  Also, I assume that every person that is tracking me will have to re-track me.
