### ISSUE TITLE
Can't login via command line

### ISSUE THREAD

**Issue by ilsken** [keybase/keybase-issues#1769]
When I try to login I get this error:
```
error: Previous payload hash doesn't match, expected: a05c5533c3a0be260c2c61d3e026c7f0ed9f050cf7fb1b3375561e9b74900f39 got: 3803be27ec0c61b3fdcd8b9b7c78de3df73766736ef00727267858d34a039c7d
```

I've deleted/recreated my proofs and public key and it still does not work (even tried on a fresh machine, no luck)

**Comment by maxtaco** [comment]
Related to #1765.  Let me look into it.  Thanks.

**Comment by ilsken** [comment]
@maxtaco I apologize for the duplicate, I had searched issues before but I must of missed that one. Glad to hear it's not just me though, looking forward to hearing back from you when it's fixed!

**Comment by maxtaco** [comment]
No need to apologize, it's a different expression of the same problem.  The cause is due to a stray newline, but I'm drilling down on it.

**Comment by maxtaco** [comment]
We had a server-side bug on 15 Sep 2015 that errantly stripped whitespace from some signature payloads.  Here is the complete list of UIDs and signatures that were affected:

```
029fb10c61d79312d5e0db3d45561a19 140f1b7b7ba32f34ad6302d0ed78692cf1564760d78c082965dc3b8b5f7e27f10f sig
029fb10c61d79312d5e0db3d45561a19 3034e8b7d75861fc28a478b4992a8592b5478d4cbc7b87150d0b59573d731d870f sig
029fb10c61d79312d5e0db3d45561a19 ac6e225b8324c1fcbe814382e198495bea801dfeb56cb22b9e89066cc52ab03b0f sig
029fb10c61d79312d5e0db3d45561a19 aea7c8f7726871714e777ac730e77e1905a38e9587f9504b739ff9b77ef2d5cc0f sig
17ed3e048fed349aad4267d1086fe619 0ff29c1d036c3f4841f3f485e28d77351abb3eeeb52d2f8d802fd15e383d9a5f0f sig
17ed3e048fed349aad4267d1086fe619 30831001edee5e01c3b5f5850043f9ef7749a1ed8624dc703ae0922e1d0f16dd0f sig
17ed3e048fed349aad4267d1086fe619 b9ee3b46c97d48742a73e35494d3a373602460609e3c6c54a553fc4d83b659e40f sig
17ed3e048fed349aad4267d1086fe619 de43758b653b3383aca640a96c7890458eadd35242e8f8531f29b606890a14ea0f sig
229a83b6e6a63e88ab5dbc3fdc1d7419 44847743878bd56f5cd74980475e8f4e95d0d6ec1dd8722fd7cfc7761698ec780f hash
33d6ed2df7e25cb985071d4028aa0119 70c4026afec66312456b6820492b7936bff42b58ca7a035729462700677ef4190f hash
4ec632fae16af1a2f744626a95ac6d19 7591a920a5050de28faad24b5fe3336f658b964e0e64464b70878bfcf04537420f hash
5c6a3b34778cf816edf36b9ac0880800 88e6c581dbccbf390559bcb30ca21548ba0ec4861ec2d666217bd4ed4a4a8c3f0f sig
5c6a3b34778cf816edf36b9ac0880800 9ba23a9a1796fb22b3c938f1edf5aba4ca5be7959d9151895eb6aa7a8d8ade420f sig
619e6eddd3df78745ecc4b3755295b19 595a73fc649c2c8ccc1aa79384e0b3e7ab3049d8df838f75ef0edbcb5bbc42990f sig
619e6eddd3df78745ecc4b3755295b19 9c189d6d644bad9596f78519d870a685624f813afc1d0e49155073d3b0521f970f sig
619e6eddd3df78745ecc4b3755295b19 e256078702afd7a15a24681259935b48342a49840ab6a90291b300961669790f0f sig
7a31a6774925f936450ad0163c5f0500 10a45e10ff2585b03b9b5bc449cb1a7a44fbb7fcf25565286cb2d969ad9b89ae0f hash
b0b958214c599307341b8200ae33b200 062e6799f211177023bc310fd6e4e28a8e2e18f972d9b037d24434a203aca7240f hash
b387c7517d93e953796181c0e6351919 031b506b705926ea962e59046bfe1720dcf72c85310502020e2ae836b294fcde0f sig
b387c7517d93e953796181c0e6351919 110a64513b4188eca2af6406a8a6dbf278dfce324b8879b5cb67e8626ff2af180f sig
b387c7517d93e953796181c0e6351919 1454fec21489f17a6d78927af1c9dca4209360c6ef6bfa569d8b62d32e668ea30f sig
b387c7517d93e953796181c0e6351919 2415e1c77b0815661452ea683e366c6d9dfd2008a7dbc907004c3a33e56cf6190f sig
b387c7517d93e953796181c0e6351919 2785b24acd6869e1e7d38a91793af549f3c35cd0729127d200b66f8c0ffba59b0f sig
b387c7517d93e953796181c0e6351919 2892863758cdaf9796fb36e2466093762efda94e74eb51e3ab9d6bec54064b8a0f sig
b387c7517d93e953796181c0e6351919 2e08f0b9566e15fa1f9e67b236e5385cdb38d57ff51d7ab3e568532867c9f8890f sig
b387c7517d93e953796181c0e6351919 3042dbe45383b0c2eafe13a73da35c4e721be026d7908dfcef6eb121d95b75b10f sig
b387c7517d93e953796181c0e6351919 47d349b8bb3c8457449390ca2ed5e489a70ad511ab3edb4c7f0af27eed8c65d30f sig
b387c7517d93e953796181c0e6351919 503df567f98cf5910ba44cb95e157e656afe95d159a15c7df4e88ac6016c948f0f sig
b387c7517d93e953796181c0e6351919 50ba350ddc388f7c6fdba032a7d283e4caa0ca656f92f69257213222dd7deeaf0f sig
b387c7517d93e953796181c0e6351919 803854b4074d668e1761ee9c533c0fc576bd0404cf26ff7545e14512f3b9002f0f sig
b387c7517d93e953796181c0e6351919 8182f385c347fe57d3c46fe40e8df0e2d6cabdac38f490417b313050249be9dc0f sig
b387c7517d93e953796181c0e6351919 833f27edcf54cc489795df1dc7d9f0cbea8253e1b84f5e82749a7a2a4ffc295c0f sig
b387c7517d93e953796181c0e6351919 a5c4a30d1eaaf752df424bf813c5a907a5cf94fd371e280d39e0a3d078310fba0f sig
b387c7517d93e953796181c0e6351919 b385c0c76d790aba156ff68fd571171fc7cb85f75e7fc9d1561d7960d8875acb0f sig
b387c7517d93e953796181c0e6351919 ba68052597a3782f64079d7d9ec821ea9785c0868e44b597a04c9cd8bf634c1e0f sig
b387c7517d93e953796181c0e6351919 c7d26afbc1957ecca890d8d9001a9cc4863490161720ad76a2aedeb8c2d50df70f sig
b387c7517d93e953796181c0e6351919 cb97f4b62f2e817e8db8c6193440214ad20f906571e4851db186869f0b4c0e310f sig
b387c7517d93e953796181c0e6351919 db8d59151b2f78c82c095c9545f1e4d39947a0c0bcc01b907e0ace14517d39970f sig
b387c7517d93e953796181c0e6351919 e088beccfee26c5df39239023d1e4e0cbcd63fd50d0bdc4bf2c2ba25ef1a8fe40f sig
b387c7517d93e953796181c0e6351919 e1d60584995e677254f7d913b3f40060b5500241d6de0c5822ba1282acc5e08b0f sig
c0af9efbb4ade7f5f550528e23255300 db9a0afaab297048be0d44ffd6d89a3eb6a003256426d7fd87a60ab59880f8160f hash
f1c263462dd526695c458af924977719 3e61901f50508aba72f12740fda2be488571afc51d718d845e339e5d1d1b531d0f sig
f1c263462dd526695c458af924977719 4db0fe3973b3a666c7830fcb39d93282f8bc414eca1d535033a5cc625eabda0c0f sig
f1c263462dd526695c458af924977719 a32692af33e559e00a40aa3bb4004744d2c1083112468ed1c8040eaacd15c6eb0f sig
f1c263462dd526695c458af924977719 df0005f6c61bd6efd2867b320013800781f7f047e83fd44d484c2cb2616f019f0f sig
f1c263462dd526695c458af924977719 eb1a13c6b6e42bb7470e222b51d36144a25ffc4fbc0b32e9a1ec11f059001bc80f sig
f8d912fe4c9bc3896430dee94aef5d00 58bf751ddd23065a820449701f8a1a0a46019e1c54612ea0867086dbd405589a0f hash
```

**Comment by maxtaco** [comment]
These users were affected:

029fb10c61d79312d5e0db3d45561a19
17ed3e048fed349aad4267d1086fe619
229a83b6e6a63e88ab5dbc3fdc1d7419
**33d6ed2df7e25cb985071d4028aa0119** (you)
4ec632fae16af1a2f744626a95ac6d19
5c6a3b34778cf816edf36b9ac0880800
619e6eddd3df78745ecc4b3755295b19
7a31a6774925f936450ad0163c5f0500
b0b958214c599307341b8200ae33b200
b387c7517d93e953796181c0e6351919
c0af9efbb4ade7f5f550528e23255300
f1c263462dd526695c458af924977719
f8d912fe4c9bc3896430dee94aef5d00

**Comment by maxtaco** [comment]
We have a bunch of us traveling over the next few days, but we have a fix in the work, it will a combination of a tweak to the server DB and a command line fix.  We'll let you know when it's ready.  Thanks for your feedback!

**Comment by maxtaco** [comment]
Should be fixed now in @v0.8.19, let me know if not. Thanks for your feedback!

**Comment by ilsken** [comment]
Hello,

I'm still unable to login (cleared cache and config too) after the update. I'm getting an error in sigchain.js. Stacktrace:
```
usr/local/lib/node_modules/keybase/lib/sigchain.js:133
                return _next(err != null ? (log.error("Couldn't find link: " + last), log.debug("| -> error")) : typeof link !== "undefined" && link !== null ? (links.push(link), curr = link.prev(), log.debug("| -> found link and previous; prev=" + curr)) : (log.debug("| -> reached the chain end"), curr = null));
                                                                               ^

ReferenceError: last is not defined
    at /usr/local/lib/node_modules/keybase/lib/sigchain.js:133:80
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /usr/local/lib/node_modules/keybase/lib/chainlink.js:316:18
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
````

**Comment by ilsken** [comment]
Version:
```
➜  ~  keybase --version
0.8.20

 
{ name: 'keybase',
  description: 'CLI interface to keybase.io',
  'dist-tags': { latest: '0.8.20' },
  versions: 
   [ '0.0.0',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.10',
     '0.0.11',
     '0.0.12',
     '0.0.13',
     '0.0.15',
     '0.0.16',
     '0.0.17',
     '0.0.18',
     '0.0.19',
     '0.0.20',
     '0.0.21',
     '0.0.22',
     '0.0.23',
     '0.0.24',
     '0.0.25',
     '0.0.26',
     '0.0.27',
     '0.0.28',
     '0.0.29',
     '0.0.30',
     '0.0.31',
     '0.0.32',
     '0.0.33',
     '0.0.34',
     '0.0.35',
     '0.0.36',
     '0.0.37',
     '0.0.38',
     '0.0.39',
     '0.0.40',
     '0.0.41',
     '0.0.42',
     '0.0.43',
     '0.0.44',
     '0.1.1',
     '0.1.2',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6',
     '0.2.7',
     '0.2.8',
     '0.2.9',
     '0.2.10',
     '0.2.11',
     '0.2.12',
     '0.2.13',
     '0.2.14',
     '0.2.15',
     '0.2.16',
     '0.2.17',
     '0.2.18',
     '0.2.19',
     '0.2.20',
     '0.2.21',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.3.3',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.4.3',
     '0.4.4',
     '0.4.5',
     '0.4.6',
     '0.4.7',
     '0.4.8',
     '0.4.9',
     '0.4.10',
     '0.4.11',
     '0.4.12',
     '0.4.13',
     '0.4.14',
     '0.4.15',
     '0.4.16',
     '0.4.17',
     '0.4.18',
     '0.4.19',
     '0.4.20',
     '0.4.21',
     '0.4.22',
     '0.5.0',
     '0.5.1',
     '0.6.0',
     '0.6.1',
     '0.6.2',
     '0.7.0',
     '0.7.1',
     '0.7.2',
     '0.7.3',
     '0.7.4',
     '0.7.5',
     '0.7.6',
     '0.7.7',
     '0.7.8',
     '0.7.9',
     '0.8.0',
     '0.8.1',
     '0.8.2',
     '0.8.3',
     '0.8.4',
     '0.8.5',
     '0.8.6',
     '0.8.7',
     '0.8.8',
     '0.8.9',
     '0.8.10',
     '0.8.11',
     '0.8.12',
     '0.8.13',
     '0.8.14',
     '0.8.15',
     '0.8.16',
     '0.8.17',
     '0.8.18',
     '0.8.19',
     '0.8.20' ],
  maintainers: 
   [ 'maxtaco <themax@gmail.com>',
     'oconnor663 <oconnor663@gmail.com>' ],
  time: 
   { modified: '2015-09-21T22:12:06.597Z',
     created: '2013-10-25T17:52:31.485Z',
     '0.0.0': '2013-10-25T17:52:32.506Z',
     '0.0.4': '2014-02-10T22:09:22.619Z',
     '0.0.5': '2014-02-13T16:54:32.990Z',
     '0.0.6': '2014-02-13T19:34:12.671Z',
     '0.0.7': '2014-02-13T21:22:29.240Z',
     '0.0.8': '2014-02-14T20:27:34.255Z',
     '0.0.10': '2014-02-14T21:32:36.284Z',
     '0.0.11': '2014-02-17T18:12:04.944Z',
     '0.0.12': '2014-02-17T23:02:14.013Z',
     '0.0.13': '2014-02-17T23:24:47.354Z',
     '0.0.15': '2014-02-18T21:19:48.384Z',
     '0.0.16': '2014-02-19T02:10:58.182Z',
     '0.0.17': '2014-02-19T14:23:16.085Z',
     '0.0.18': '2014-02-20T17:14:33.424Z',
     '0.0.19': '2014-02-20T18:13:48.943Z',
     '0.0.20': '2014-02-21T20:51:34.537Z',
     '0.0.21': '2014-02-21T22:01:49.823Z',
     '0.0.22': '2014-02-24T18:36:47.824Z',
     '0.0.23': '2014-02-25T14:29:37.660Z',
     '0.0.24': '2014-02-25T22:15:34.576Z',
     '0.0.25': '2014-02-26T20:29:01.431Z',
     '0.0.26': '2014-02-26T21:05:45.971Z',
     '0.0.27': '2014-02-26T22:49:24.990Z',
     '0.0.28': '2014-02-27T19:48:06.688Z',
     '0.0.29': '2014-02-28T14:59:16.475Z',
     '0.0.30': '2014-02-28T23:51:07.634Z',
     '0.0.31': '2014-03-03T14:29:46.419Z',
     '0.0.32': '2014-03-10T12:54:23.969Z',
     '0.0.33': '2014-03-10T18:22:29.081Z',
     '0.0.34': '2014-03-11T13:23:01.110Z',
     '0.0.35': '2014-03-12T21:02:59.963Z',
     '0.0.36': '2014-03-12T21:22:33.614Z',
     '0.0.37': '2014-03-13T12:43:25.002Z',
     '0.0.38': '2014-03-13T18:20:16.292Z',
     '0.0.39': '2014-03-15T23:54:21.411Z',
     '0.0.40': '2014-03-18T20:29:45.798Z',
     '0.0.41': '2014-03-20T18:27:28.175Z',
     '0.0.42': '2014-03-21T17:53:10.388Z',
     '0.0.43': '2014-03-22T22:40:12.151Z',
     '0.0.44': '2014-03-24T14:34:38.626Z',
     '0.1.1': '2014-03-26T19:21:41.885Z',
     '0.1.2': '2014-03-26T19:24:40.973Z',
     '0.2.0': '2014-03-26T20:59:09.677Z',
     '0.2.1': '2014-03-27T18:06:53.981Z',
     '0.2.2': '2014-03-27T21:38:18.244Z',
     '0.2.3': '2014-03-28T12:44:14.080Z',
     '0.2.4': '2014-03-28T14:37:45.494Z',
     '0.2.5': '2014-03-28T23:28:35.721Z',
     '0.2.6': '2014-03-28T23:33:28.747Z',
     '0.2.7': '2014-03-29T13:40:28.528Z',
     '0.2.8': '2014-03-29T16:59:29.813Z',
     '0.2.9': '2014-03-29T17:04:04.302Z',
     '0.2.10': '2014-03-30T17:58:29.953Z',
     '0.2.11': '2014-03-31T15:11:25.395Z',
     '0.2.12': '2014-04-01T13:43:08.441Z',
     '0.2.13': '2014-04-01T20:00:00.701Z',
     '0.2.14': '2014-04-02T17:09:54.101Z',
     '0.2.15': '2014-04-02T19:00:18.397Z',
     '0.2.16': '2014-04-02T22:07:26.649Z',
     '0.2.17': '2014-04-05T00:04:00.707Z',
     '0.2.18': '2014-04-05T00:28:37.898Z',
     '0.2.19': '2014-04-09T18:21:50.987Z',
     '0.2.20': '2014-04-11T23:08:48.483Z',
     '0.2.21': '2014-04-11T23:28:51.217Z',
     '0.3.0': '2014-04-28T21:26:36.505Z',
     '0.3.1': '2014-04-29T11:25:23.347Z',
     '0.3.2': '2014-04-29T17:43:10.523Z',
     '0.3.3': '2014-05-16T00:06:10.572Z',
     '0.4.0': '2014-05-21T18:21:48.234Z',
     '0.4.1': '2014-06-04T20:13:54.020Z',
     '0.4.2': '2014-06-04T23:22:29.248Z',
     '0.4.3': '2014-06-05T14:36:10.866Z',
     '0.4.4': '2014-06-07T20:43:33.683Z',
     '0.4.5': '2014-06-12T18:38:15.534Z',
     '0.4.6': '2014-06-12T18:55:06.992Z',
     '0.4.7': '2014-06-12T21:44:56.045Z',
     '0.4.8': '2014-06-19T17:58:42.774Z',
     '0.4.9': '2014-06-20T15:24:24.382Z',
     '0.4.10': '2014-06-24T17:12:58.036Z',
     '0.4.11': '2014-06-24T17:23:41.294Z',
     '0.4.12': '2014-08-04T15:50:59.155Z',
     '0.4.13': '2014-08-04T20:11:27.578Z',
     '0.4.14': '2014-08-04T21:37:50.092Z',
     '0.4.15': '2014-08-11T14:40:33.731Z',
     '0.4.16': '2014-08-15T01:30:11.706Z',
     '0.4.17': '2014-08-18T15:13:09.354Z',
     '0.4.18': '2014-08-18T20:36:41.283Z',
     '0.4.19': '2014-08-20T16:49:42.943Z',
     '0.4.20': '2014-08-22T14:59:12.002Z',
     '0.4.21': '2014-08-22T15:11:23.494Z',
     '0.4.22': '2014-08-22T15:21:09.617Z',
     '0.5.0': '2014-08-28T14:20:35.564Z',
     '0.5.1': '2014-08-28T14:51:42.288Z',
     '0.6.0': '2014-09-16T21:21:20.023Z',
     '0.6.1': '2014-09-18T21:06:27.632Z',
     '0.6.2': '2014-09-19T15:43:22.501Z',
     '0.7.0': '2014-09-22T17:53:39.629Z',
     '0.7.1': '2014-09-23T13:46:24.999Z',
     '0.7.2': '2014-09-24T15:48:44.946Z',
     '0.7.3': '2014-11-17T15:43:08.148Z',
     '0.7.4': '2015-02-06T15:20:40.984Z',
     '0.7.5': '2015-02-09T14:24:14.723Z',
     '0.7.6': '2015-02-19T22:07:28.124Z',
     '0.7.7': '2015-02-20T21:25:49.956Z',
     '0.7.8': '2015-04-24T17:43:18.345Z',
     '0.7.9': '2015-05-27T13:16:32.310Z',
     '0.8.0': '2015-07-01T16:20:09.688Z',
     '0.8.1': '2015-07-01T20:55:20.515Z',
     '0.8.2': '2015-07-01T21:36:49.226Z',
     '0.8.3': '2015-07-02T00:03:08.386Z',
     '0.8.4': '2015-07-02T21:30:04.289Z',
     '0.8.5': '2015-07-03T03:02:43.267Z',
     '0.8.6': '2015-07-03T18:41:10.626Z',
     '0.8.7': '2015-07-05T13:30:52.048Z',
     '0.8.8': '2015-07-05T23:34:27.179Z',
     '0.8.9': '2015-07-08T15:30:18.636Z',
     '0.8.10': '2015-07-16T15:38:37.514Z',
     '0.8.11': '2015-07-20T19:22:23.255Z',
     '0.8.12': '2015-07-21T18:35:22.452Z',
     '0.8.13': '2015-07-24T22:40:38.943Z',
     '0.8.14': '2015-07-25T14:07:40.711Z',
     '0.8.15': '2015-07-28T14:55:40.516Z',
     '0.8.16': '2015-07-30T15:15:38.057Z',
     '0.8.17': '2015-08-13T21:18:53.784Z',
     '0.8.18': '2015-08-14T16:07:06.331Z',
     '0.8.19': '2015-09-18T15:18:50.149Z',
     '0.8.20': '2015-09-21T22:12:06.597Z' },
  author: 'Maxwell Krohn <themax@gmail.com>',
  repository: { type: 'git', url: 'git://github.com/keybase/node-client.git' },
  readmeFilename: 'README.md',
  bugs: { url: 'https://github.com/keybase/node-client/issues' },
  license: 'BSD-3-Clause',
  users: { felixjung: true },
  homepage: 'https://github.com/keybase/node-client#readme',
  version: '0.8.20',
  bin: { keybase: './bin/main.js' },
  scripts: { test: 'make test', build: 'make build' },
  dependencies: 
   { argparse: '0.1.15',
     badnode: '^1.0.1',
     bitcoyne: '>=0.0.6',
     bn: '^1.0.1',
     cheerio: '0.13.0',
     codesign: '0.0.9',
     colors: '0.6.2',
     'deep-equal': '0.2.1',
     'framed-msgpack-rpc': '1.1.4',
     'gpg-wrapper': '>=1.0.5',
     'iced-data-structures': '0.0.5',
     'iced-db': '0.0.4',
     'iced-error': '0.0.9',
     'iced-lock': '^1.0.1',
     'iced-logger': '0.0.5',
     'iced-runtime': '>=1.0.3',
     'iced-spawn': '>=1.0.0',
     'iced-utils': '0.1.22',
     kbpgp: '>=2.0.46',
     'keybase-installer': '1.0.2',
     'keybase-path': '0.0.16',
     'keybase-proofs': '^2.0.13',
     libkeybase: '>=1.2.19',
     'merkle-tree': '0.0.14',
     mkdirp: '0.3.5',
     'pgp-utils': '>=0.0.28',
     progress: '1.1.3',
     purepack: '1.0.1',
     read: 'github:keybase/read',
     request: '^2.58.0',
     semver: '^4.0.0',
     'socks5-client': '^0.3.6',
     'socks5-http-client': '^0.1.6',
     'socks5-https-client': '^0.2.2',
     spotty: '^1.0.0',
     tablify: '0.1.5',
     timeago: '0.1.0',
     triplesec: '>=3.0.16' },
  devDependencies: 
   { 'iced-coffee-script': '~1.7.1-c',
     'iced-expect': '0.0.3',
     'iced-test': '>=0.0.16',
     optimist: '0.6.1' },
  bundleDependencies: 
   [ 'argparse',
     'badnode',
     'bitcoyne',
     'bn',
     'cheerio',
     'codesign',
     'colors',
     'deep-equal',
     'framed-msgpack-rpc',
     'gpg-wrapper',
     'iced-data-structures',
     'iced-db',
     'iced-error',
     'iced-lock',
     'iced-logger',
     'iced-runtime',
     'iced-spawn',
     'iced-utils',
     'kbpgp',
     'keybase-path',
     'keybase-proofs',
     'libkeybase',
     'merkle-tree',
     'mkdirp',
     'pgp-utils',
     'progress',
     'purepack',
     'read',
     'request',
     'semver',
     'socks5-client',
     'socks5-http-client',
     'socks5-https-client',
     'spotty',
     'tablify',
     'timeago',
     'triplesec' ],
  gitHead: '4dcbf4cb1c750ce024d4f123b1a65a0d8be03b27',
  dist: 
   { shasum: '56121b17e19feefc479ee2b699c0bcb679bf5ecb',
     tarball: 'http://registry.npmjs.org/keybase/-/keybase-0.8.20.tgz' },
  directories: {} }


```

**Comment by maxtaco** [comment]
Have you also since reset your public key?

Can you send a login trace with `-d`? Thanks

**Comment by ilsken** [comment]
Yeah I reset my key, I'm getting this error now:
`error: Found a later subchain with eldest kid 0101e60d87c6938727a8e3bd74c4d919dcbbde4dbb4f5a7e10b079bde6849564b51d0a`

Login trace:
```
➜  ~  keybase -d login
debug: + opening config file: /Users/ctarquini/.config/keybase/config.json
debug: ++ loading config file /Users/ctarquini/.config/keybase/config.json
debug: -- loaded config file -> {"user":{"name":"proservices", <SNIP>}}
debug: - opened config file; found=true
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg2
debug: - tested GPG command-line client -> null
debug: Setting GPG_TTY=/dev/ttys000
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.8.20
debug: | Platform info: {"versions":{"http_parser":"2.5.0","node":"4.0.0","v8":"4.5.103.30","uv":"1.7.3","zlib":"1.2.8","ares":"1.10.1-DEV","modules":"46","openssl":"1.0.2d"},"arch":"x64","platform":"darwin","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls_ocsp":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.8.20","- node.js v4.0.0","- gpg (GnuPG/MacGPG2) 2.0.28","- libgcrypt 1.6.3","Identifies as: 'keybase.io node.js client v0.8.20 darwin'"]
debug: - startup message
debug: + opening database file: /Users/ctarquini/.local/share/keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 0
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /Users/ctarquini/.cache/keybase/session.json
debug: -- opened config file; found=false
debug: - session::load
debug: + session::check
debug: - session::check
Your keybase login passphrase: ********************
debug: + request to getsalt (https://api.keybase.io:443/_/api/1.0/getsalt.json?email_or_username=proservices) (cookie=true)
debug: | Adding a custom CA for host api.keybase.io when tls=true
debug: - request to getsalt -> null
- run scrypt [==================================] 100%
debug: + request to login (https://api.keybase.io:443/_/api/1.0/login.json) (cookie=true)
debug: | Adding a custom CA for host api.keybase.io when tls=true
debug: - request to login -> null
debug: + session::load
debug: ++ opening config file: /Users/ctarquini/.cache/keybase/session.json
debug: -- opened config file; found=false
debug: - session::load
info: Updated file: /Users/ctarquini/.cache/keybase/session.json
debug: + KeyPull::run
debug: ++ KeyPull::load_user
debug: +++ proservices: load user
debug: ++++ proservices: load user from local storage
debug: +++++ load sig chain from local storage
debug: ||||| loading sig chain w/ payload hash 30c1e429d1d0b7d6a79f0f74a640aa24217b736a8e9e93bff795479b51a16081
debug: ++++++ 33d6ed2df7e25cb985071d4028aa0119: load signature chain
debug: |||||| 33d6ed2df7e25cb985071d4028aa0119: Loading link 30c1e429d1d0b7d6a79f0f74a640aa24217b736a8e9e93bff795479b51a16081
debug: |||||| -> found link and previous; prev=0c4ca4654a3057c836754be40241355be066065ce933bcc4585cf2d57488ab4e
debug: |||||| 33d6ed2df7e25cb985071d4028aa0119: Loading link 0c4ca4654a3057c836754be40241355be066065ce933bcc4585cf2d57488ab4e
debug: |||||| -> found link and previous; prev=fb2cc025c12eb324297e7aaf608bf197c0088ae027fe64f2ff632bf0c93c0fc9
debug: |||||| 33d6ed2df7e25cb985071d4028aa0119: Loading link fb2cc025c12eb324297e7aaf608bf197c0088ae027fe64f2ff632bf0c93c0fc9
debug: |||||| -> found link and previous; prev=6b0ebc51d443d6c9af3091ac2ceee2cb98198c508315b83240594b15666a1995
debug: |||||| 33d6ed2df7e25cb985071d4028aa0119: Loading link 6b0ebc51d443d6c9af3091ac2ceee2cb98198c508315b83240594b15666a1995
debug: |||||| -> found link and previous; prev=cc0b91911f4d928b0a122cc5a56deb9cdb37157a823493f6fdd31ac890a1efe7
debug: |||||| 33d6ed2df7e25cb985071d4028aa0119: Loading link cc0b91911f4d928b0a122cc5a56deb9cdb37157a823493f6fdd31ac890a1efe7
debug: |||||| -> found link and previous; prev=3803be27ec0c61b3fdcd8b9b7c78de3df73766736ef00727267858d34a039c7d
debug: |||||| 33d6ed2df7e25cb985071d4028aa0119: Loading link 3803be27ec0c61b3fdcd8b9b7c78de3df73766736ef00727267858d34a039c7d
debug: |||||| -> found link and previous; prev=null
debug: ------ 33d6ed2df7e25cb985071d4028aa0119: loaded signature chain
debug: ----- loaded sig chain from local storage
debug: ---- proservices: loaded user from local storage -> null / [object Object]
debug: ||| Checking session since we're loading User as self (and need secret key)
debug: ++++ session::load_and_check
debug: +++++ session::load
debug: ++++++ opening config file: /Users/ctarquini/.cache/keybase/session.json
debug: +++++++ loading config file /Users/ctarquini/.cache/keybase/session.json
debug: ------- loaded config file -> <redacted>
debug: ------ opened config file; found=true
debug: ----- session::load
debug: +++++ session::check
debug: ||||| calling to sesscheck
debug: ++++++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: |||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ------ request to sesscheck -> null
debug: ----- session::check
debug: ---- session::load_and_check -> true
debug: ++++ proservices: load user from server
debug: +++++ merkle find_and_verify: uid undefined, username proservices
debug: ++++++ request to merkle/path (https://api.keybase.io:443/_/api/1.0/merkle/path.json?uid=&username=proservices) (cookie=true)
debug: |||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ------ request to merkle/path -> null
debug: ++++++ merkle get_merkle_pgp_key
debug: |||||| Call to gpg2: { args: [ '-k', '--with-fingerprint', '--with-colons' ],
debug:   quiet: true,
debug:   no_options: true }
debug: |||||| merkle key already found in keyring
debug: ------ merkle get_merkle_pgp_key
debug: ||||| Load key /2A32340CEC8C9492 from master keyring (secret=undefined)
debug: ||||| Call to gpg2: { args:
debug:    [ '--export',
debug:      '--export-options',
debug:      'export-local-sigs',
debug:      '-a',
debug:      '2A32340CEC8C9492' ] }
debug: ++++++ lookup UID
debug: +++++++ read_uids_from_keys 03E146CDAF8136680AD566912A32340CEC8C9492
debug: ||||||| Call to gpg2: { args:
debug:    [ '-k',
debug:      '--with-fingerprint',
debug:      '--with-colons',
debug:      '03E146CDAF8136680AD566912A32340CEC8C9492' ],
debug:   quiet: true,
debug:   no_options: true }
debug: ||||||| got: [{"username":"Keybase.io Merkle Signing","comment":"v1","email":"merkle@keybase.io"}]
debug: ------- read_uids_from_key -> null
debug:  - Map 2A32340CEC8C9492 -> [object Object] via gpg
debug: ------ looked up UID
debug: ++++++ Rollback check
debug: |||||| DB put value kv:e2:6902f97e65ea5a61f062833392fe50a35bf76cd286b1d8e2f78658ca2752633ad7b87be18e997d4438dddc09abbc9d5a18524705b63c83ec103848c19d7c7686
debug: |||||| DB put lookup: lo:5:latest -> ebaea4f9d4c598b492f294d4d25f9d607508b155a7e5423342ef4a52ba2e893e
debug: ------ Rollback check
debug: ++++++ request to user/lookup (https://api.keybase.io:443/_/api/1.0/user/lookup.json?username=proservices) (cookie=true)
debug: |||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ------ request to user/lookup -> null
debug: ----- proservices: loaded user from server
debug: +++++ updating local user w/ remote
debug: ++++++ update sig chain; remote_seqno=6
debug: ------ updated sig chain
debug: ----- finished update
debug: +++++ proservices: verifying signatures
debug: ++++++ proservices: verifying sig
debug: +++++++ libkeybase: replay(username: proservices, uid: 33d6ed2df7e25cb985071d4028aa0119, eldest: 010179c28cac38659e4119ebb385e703f488915d63399a46abb2d0f44851835281540a)
debug: ||||||| libkeybase: replaying signature 1: 70c4026afec66312456b6820492b7936bff42b58ca7a035729462700677ef4190f
debug: ||||||| libkeybase: chain link parsed, type 'web_service_binding'
debug: ||||||| libkeybase: signing key is valid (010179c28cac38659e4119ebb385e703f488915d63399a46abb2d0f44851835281540a)
debug: ||||||| libkeybase: replaying signature 2: e026622f98786452f8e75168941f6137de99a15034e9c9399e846e7aa2dda50b0f
debug: ||||||| libkeybase: chain link parsed, type 'web_service_binding'
debug: ||||||| libkeybase: signing key is valid (010179c28cac38659e4119ebb385e703f488915d63399a46abb2d0f44851835281540a)
debug: ||||||| libkeybase: replaying signature 3: 13e6c6a1ec0403f1cde02c9d1c0902568539129c47ae13b20b45370cd6d2b49c0f
debug: ||||||| libkeybase: chain link parsed, type 'web_service_binding'
debug: ||||||| libkeybase: signing key is valid (010179c28cac38659e4119ebb385e703f488915d63399a46abb2d0f44851835281540a)
debug: ||||||| libkeybase: replaying signature 4: b72eed3d154132e55d2a202b8feda9cced942fb351345a5e6dbf55f15040a3d30f
debug: ||||||| libkeybase: chain link parsed, type 'web_service_binding'
debug: ||||||| libkeybase: signing key is valid (010179c28cac38659e4119ebb385e703f488915d63399a46abb2d0f44851835281540a)
debug: ||||||| libkeybase: replaying signature 5: b93437e2a2953c8a3f100f5ae10886620aa152bb871329aa4fff5c354f7fb7480f
debug: ||||||| libkeybase: chain link parsed, type 'web_service_binding'
error: Found a later subchain with eldest kid 0101e60d87c6938727a8e3bd74c4d919dcbbde4dbb4f5a7e10b079bde6849564b51d0a
````

**Comment by maxtaco** [comment]
We might not get to this right away, but we'll get to it. Thanks for your patience.

**Comment by oconnor663** [comment]
@ilsken the error you're seeing is because you reset your account but then reuploaded a key that you'd used before. We've gone back and forth about whether that's allowed -- right now it isn't, and I thought the server prevented it, but it looks like I was wrong.

The immediate workaround is to do another reset and just use a new key. Would that work for you?

**Comment by ilsken** [comment]
@oconnor663 Ah! Some validation or even just a better error message would be much a nice touch. Thanks for all your help, I generated a new key and everything is working great.

**Comment by oconnor663** [comment]
Awesome. It should be a pretty small server-side change to prevent this. Thanks for putting up with us in the meantime.

(Note for the future: This limitation only applies to your eldest key, so in the future where eldest keys are usually internally-generated device keys, people won't really run into this. You'll end up adding PGP keys to your account as "sibling keys", and as an upside you will be able to have more than one.)
