### ISSUE TITLE
keybase passphrase recover Fails

### ISSUE THREAD

**Issue by simotek** [keybase/keybase-issues#1956]
user@host ~/Downloads➤  keybase passphrase recover
Password recovery will put your account on probation for 5 days.
You won't be able to perform certain actions, like revoking devices.
Continue with password recovery? (type 'YES' to confirm): YES
▶ ERROR protocol not found: keybase.1.secretUi

user@host ~/Downloads➤ keybase --version
keybase version 1.0.7-0

Happy to provide more info / testing

Running on openSUSE 42.1

**Comment by davejlong** [comment]
Same issue on Mac:

```
$ keybase passphrase recover
Password recovery will put your account on probation for 5 days.
You won't be able to perform certain actions, like revoking devices.
Continue with password recovery? (type 'YES' to confirm): YES
▶ ERROR protocol not found: keybase.1.secretUi
$ keybase --version
keybase version 1.0.7-0
$ uname -a
Darwin Davids-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

**Comment by maxtaco** [comment]
Gah. Easy fix we can likely fix it today but no immediate promises on when
we can cut a release.  Stay tuned! And thanks!

**Comment by patrickxb** [comment]
This was already fixed in master 6 days ago:

https://github.com/keybase/client/commit/c8f91ba24662513ba13589e448e389de80a8b56d

**Comment by simotek** [comment]
When I have a spare 10 minutes to learn how to build go apps i'll have a shot at testing master.

**Comment by patrickxb** [comment]
It should be fixed in 1.0.8, which is available now.

**Comment by simotek** [comment]
Now i get the following 

    simon@host ~➤  keybase passphrase recover
    ▶ INFO Forking background server with pid=1899
    Password recovery will put your account on probation for 5 days.
    You won't be able to perform certain actions, like revoking devices.
    Continue with password recovery? (type 'YES' to confirm): YES
    ▶ ERROR {unix:///run/user/1000/keybase/keybased.sock} Error in transport: RPC error: type 0, length 4, error: protocol not found: keybase.1.secretUi
    ▶ WARNING {unix:///run/user/1000/keybase/keybased.sock} asynchronous t.run() failed with RPC error: type 0, length 4, error: protocol not found: keybase.1.secretUi
    ▶ ERROR EOF
    simon@host ~➤  keybase --version          Fri Jan 15 22:22:59 ACDT 2016 - 0
    keybase version 1.0.8-0
    simon@host ~➤                             Fri Jan 15 22:25:18 ACDT 2016 - 0

**Comment by maxtaco** [comment]
Jeez, very sorry, I've never seen this bug before.  What does `keybase version` say?

**Comment by simotek** [comment]
keybase version 1.0.8-0 

Pulled the latest 10 minutes ago

**Comment by maxtaco** [comment]
Can you paste the actual output?

**Comment by simotek** [comment]
simon@HOST ~➤  keybase --version         
keybase version 1.0.8-0

**Comment by maxtaco** [comment]
Right, but I meant `keybase version`, without the double-hyphens.  This is a command that actually communicates with the background daemon.  I wanted to test that that works.

**Comment by simotek** [comment]
ahh sure didn't realize there was a difference

    simon@host ~➤  keybase version
    Client:  1.0.8-0
    Service: 1.0.8-0

**Comment by maxtaco** [comment]
Ok, thanks.  And something like `keybase id max` also works took?

**Comment by maxtaco** [comment]
Also, did you build from source?

**Comment by simotek** [comment]
`keybase id max` seems to work fine, I attempted to build from source but gave up before it built and downloaded the package instead, I have since run `sudo rm -rf /usr/lib64/go/src/github.com/keybase/` and rebooted

    simon@Host ~➤  which keybase 
    /usr/bin/keybase

**Comment by maxtaco** [comment]
Ok,thanks so much for the feedback.  I'll investigate right now.

**Comment by maxtaco** [comment]
Ok, repro'ed in master.  Sorry about the false promise, we'll push out a fix soon.

**Comment by simotek** [comment]
No probs, Happy to test again when its ready.

**Comment by maxtaco** [comment]
@patrickxb, `passphrase change` was fixed but not `passphrase recover`

**Comment by simotek** [comment]
Confirmed fixed in the latest version.

**Comment by linneman** [comment]
After upgrading brew, I get still an error under Mac OS X:

olaris:~ ol$ keybase passphrase recover
▶ ERROR protocol not found: keybase.1.log
solaris:~ ol$ keybase --version
keybase version 1.0.9-0

**Comment by maxtaco** [comment]
Try 'pkill service' and try again.

**Comment by maxtaco** [comment]
I meant 'pkill keybase'

**Comment by nbarbettini** [comment]
I also have version
```
Client:  1.0.8-0
Service: 1.0.8-0
```

and `keybase passphrase recover` doesn't work.

Is `keybase update check` the right way to get the latest version?

**Comment by maxtaco** [comment]
What platform are you on?  Also, why did recover fail?

**Comment by nbarbettini** [comment]
Sorry, should have included more information. I get the same error as simotek:
```
➜  ~ keybase passphrase recover
Password recovery will put your account on probation for 5 days.
You won't be able to perform certain actions, like revoking devices.
Continue with password recovery? (type 'YES' to confirm): YES
▶ ERROR {unix:///Users/nate/Library/Caches/Keybase/keybased.sock} Error in transport: RPC error: type 0, length 4, error: protocol not found: keybase.1.secretUi
▶ ERROR EOF
```

I'm on OS X El Capitan. Happy to provide any further info!

**Comment by maxtaco** [comment]
Ah ok.  Yeah, I'd upgrade via `brew` since presumably that's the way you installed it, right?

**Comment by nbarbettini** [comment]
Ah, makes sense. Yep, installed via `brew`. All good! Thanks.
