### ISSUE TITLE
Blockchain checker tool is throwing errors

### ISSUE THREAD

**Issue by RyanSinger** [keybase/keybase-issues#2085]
Check it out:

```
Progress	
info: Most recent TX from 1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz is 8aa70ab2cd112742057780db1b24d020dbaa01f66e4a279b1b264da43cfbb25c

info: Got BTC to address: 1E3YfpUNUrv8RYxejKVcfGjvibGB7BRjjS

info: to hash -> 8f14e73ea7989400e5c6c30a756718afac2c99a6

debug: + lookup userid Ryan_Singer

info: Map: Ryan_Singer -> 295af46f507c858f3b24747ebc2e3700

debug: - lookup userid

info: Lookup merkle node d01985804596ad79cf1a1f74a5393fe700442033d3c9c02823262388ef4f2da2f12f985f857e2099b2f04ff63f8537fba9e42db4dd3ad1ed389212f16429519b

info: Lookup merkle node 0a551d611ec3060f51e7b5765272db324b7c6cee086e17185d8afe79016d61737ed7caf923dae47e298f1a2c6d46196124256278f6acd637212b0bfd9730fefe

info: Most recent TX from 1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz is 8aa70ab2cd112742057780db1b24d020dbaa01f66e4a279b1b264da43cfbb25c

info: Got BTC to address: 1E3YfpUNUrv8RYxejKVcfGjvibGB7BRjjS

info: to hash -> 8f14e73ea7989400e5c6c30a756718afac2c99a6

debug: + lookup userid jgcrossman2

info: Map: jgcrossman2 -> 10c2febcb3a7a5b54babfd9b4dcf6119

debug: - lookup userid

info: Lookup merkle node d01985804596ad79cf1a1f74a5393fe700442033d3c9c02823262388ef4f2da2f12f985f857e2099b2f04ff63f8537fba9e42db4dd3ad1ed389212f16429519b

info: Lookup merkle node 899a9c387aefa2663dd717ab6a28fb6a533489888956759bf4f4a19daffa2780c237afe57a07cfdbfea509cc6fa78e4d2d543d5dd8192804df895816012c3aef

Results	
Errors	
Error: Bad hash: f5b78028fdee7c15bc64f856a01b1da24192e724501aba221e1d4a22ddd999e3 != 117,f5b78028fdee7c15bc64f856a01b1da24192e724501aba221e1d4a22ddd999e3,148888b6a4b42da6fa8ad914a7ed5af879c1844dfa9bcaa99da8f16e43d3f60f

Error: Bad hash: d35a8b0a9b215907416a540511d1f962f019009d707f7c1378113256de92032d != 15,d35a8b0a9b215907416a540511d1f962f019009d707f7c1378113256de92032d,4aea7c4a905d220f1f5afadc3b0ec4081341683892ea8f37170eec3ed95c52f7
```

**Comment by maxtaco** [comment]
Gah thanks for the bug report.  We changed the leaf format.  We will check
it out.....

**Comment by maxtaco** [comment]
Remind me... where is this script? :)

**Comment by RyanSinger** [comment]
https://github.com/keybase/blockchain

**Comment by maxtaco** [comment]
Thanks for the bug report, should be fixed.

**Comment by RyanSinger** [comment]
Still broken

info: Most recent TX from 1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz is 8aa70ab2cd112742057780db1b24d020dbaa01f66e4a279b1b264da43cfbb25c

info: Got BTC to address: 1E3YfpUNUrv8RYxejKVcfGjvibGB7BRjjS

info: to hash -> 8f14e73ea7989400e5c6c30a756718afac2c99a6

debug: + lookup userid Ryan_Singer

info: Map: Ryan_Singer -> 295af46f507c858f3b24747ebc2e3700

debug: - lookup userid

info: Lookup merkle node d01985804596ad79cf1a1f74a5393fe700442033d3c9c02823262388ef4f2da2f12f985f857e2099b2f04ff63f8537fba9e42db4dd3ad1ed389212f16429519b

info: Lookup merkle node 0a551d611ec3060f51e7b5765272db324b7c6cee086e17185d8afe79016d61737ed7caf923dae47e298f1a2c6d46196124256278f6acd637212b0bfd9730fefe

Results	
Errors	
Error: Bad hash: f5b78028fdee7c15bc64f856a01b1da24192e724501aba221e1d4a22ddd999e3 != 117,f5b78028fdee7c15bc64f856a01b1da24192e724501aba221e1d4a22ddd999e3,148888b6a4b42da6fa8ad914a7ed5af879c1844dfa9bcaa99da8f16e43d3f60f

**Comment by maxtaco** [comment]
Did you install out of npm or out of the git repo?

**Comment by maxtaco** [comment]
I get:

```
[max@meuse ~/src/keybase/blockchain ] ./bin/main.js Ryan_Singer
info: Most recent TX from 1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz is 8aa70ab2cd112742057780db1b24d020dbaa01f66e4a279b1b264da43cfbb25c
info: Got BTC to address: 1E3YfpUNUrv8RYxejKVcfGjvibGB7BRjjS
info:  to hash -> 8f14e73ea7989400e5c6c30a756718afac2c99a6
info: Map: Ryan_Singer -> 295af46f507c858f3b24747ebc2e3700
info: Lookup merkle node d01985804596ad79cf1a1f74a5393fe700442033d3c9c02823262388ef4f2da2f12f985f857e2099b2f04ff63f8537fba9e42db4dd3ad1ed389212f16429519b
info: Lookup merkle node 0a551d611ec3060f51e7b5765272db324b7c6cee086e17185d8afe79016d61737ed7caf923dae47e298f1a2c6d46196124256278f6acd637212b0bfd9730fefe
info: User triple: [2,[117,"f5b78028fdee7c15bc64f856a01b1da24192e724501aba221e1d4a22ddd999e3","148888b6a4b42da6fa8ad914a7ed5af879c1844dfa9bcaa99da8f16e43d3f60f"],[],"0101d1c7dd0e0e4418d453dd2c427cbaf37b0a1485f9bbfb0f66e34580eee34968200a"]
info: Chain checked out
{ body: 
   { device: 
      { ctime: 0,
        id: 'e0feb519782c88a2a422017f009fba18',
        kid: '012118a3ccc957e68b873af226fc4fbffebc7963117f52b90a56a60a18928aed2d580a',
        mtime: 0,
        status: 1 },
     key: 
      { eldest_kid: '0101d1c7dd0e0e4418d453dd2c427cbaf37b0a1485f9bbfb0f66e34580eee34968200a',
        host: 'keybase.io',
        kid: '012013f3a46873fca71ab90ece98ba775522d55eda211ab5f20f4da080ccdf6a1c660a',
        uid: '295af46f507c858f3b24747ebc2e3700',
        username: 'ryan_singer' },
     subkey: 
      { kid: '012118a3ccc957e68b873af226fc4fbffebc7963117f52b90a56a60a18928aed2d580a',
        parent_kid: '012013f3a46873fca71ab90ece98ba775522d55eda211ab5f20f4da080ccdf6a1c660a' },
     type: 'subkey',
     version: 1 },
  client: { name: 'keybase.io go client', version: '1.0.11' },
  ctime: 1455599047,
  expire_in: 504576000,
  merkle_root: 
   { ctime: 1455598437,
     hash: '6b199086419d57f5f4c07dcc8200684ab772562d40044c82593bcdbd26d53192d4b0022fc2930ccb08d96fe5ae019668e9b5bfc8dc8c21dcbbb8b22a4cd1beb0',
     seqno: 386126 },
  prev: 'e7b60cb22fce8bf752e582f4d286dd53df24a2510259e4af00117b0298014466',
  seqno: 117,
  tag: 'signature' }
```

**Comment by RyanSinger** [comment]
I downloaded the zip file of the git repo and opened index.html

**Comment by maxtaco** [comment]
Forgot all about that!  @malgorithms would not be happy with such a monstrosity.  Anyways, try again?

**Comment by RyanSinger** [comment]
It now works!

Good work!
