### ISSUE TITLE
Facebook Verification Call Fails

### ISSUE THREAD

**Issue by niall-byrne** [keybase/keybase-issues#2974]
Hi There,

When adding my proof to facebook, via web, or osx client, the posting link fires a callback that returns a 403, and the proof is stuck in an unreachable state.

Here's the call back it fires after posting (I believe this is the right one, I've tried this several times now):
https://keybase.io/_/facebook_callback?sig_id_med=qXoS9WN9bN3iKAQNx85Z7hfFI454Vx0Q1k9_No1Cnvc&token=lgHZIDFlN2VhZjE2MTI4ODdjZjU1ODE1YzkxODU2N2QyNTE5zlkW%2BWDOAAP0gMDEIHNqJ2g60fH3DhjWAEmO9J8T67p%2F7vlgyjDZKjKOM02l#_=_

And the post itself:
https://www.facebook.com/ninebyrne/posts/1933217586965252

Oh and my keybase profile:
https://keybase.io/niallbyrne

**Comment by maxtaco** [comment]
CC: @oconnor663

**Comment by manibatra** [comment]
Having the same issue for the Facebook profile manibatra23

Here is the post : 

https://www.facebook.com/manibatra23/posts/10155266038026197?pnref=story

**Comment by oconnor663** [comment]
Same issue as https://github.com/keybase/client/issues/6988.

I do have a repro for this locally. The server error is `missing non-optional field post_id`. Something might've changed on Facebook's end. Digging...

**Comment by oconnor663** [comment]
The issue is that Facebook just changed how the facebook.com/dialog/feed flow works. See the deprecation notice here: https://developers.facebook.com/docs/sharing/reference/feed-dialog#response. I think we started depending on that feature shortly before it was deprecated, and I missed the notice.

**Comment by oconnor663** [comment]
This will probably not be fixable in less than a day. In the meantime, we might want to disable new Facebook proofs more explicitly. Sorry for all the trouble here, folks.

**Comment by oconnor663** [comment]
I've pushed a small server change that should at least make the error message clearer:

![image](https://cloud.githubusercontent.com/assets/860932/26036530/51070fa6-38ad-11e7-9eca-83d156a6f987.png)

**Comment by SamuelEnglard** [comment]
@oconnor663 I'd make that error message appear sooner than it does currently.

**Comment by oconnor663** [comment]
Yes, I agree that it's terrible, but this is the first error we get a chance to show with just a server-side change. A much nicer thing to do would be to gray out / hide the entire Facebook section, but that requires shipping client-side changes, which I don't want to rush out on a weekend.

**Comment by SamuelEnglard** [comment]
@oconnor663 I get that, but at the same time as an end user it's very confusing. No winning here so yeah

**Comment by oconnor663** [comment]
New proof flow is in review/testing.

**Comment by m4xch3** [comment]
<img width="410" alt="2017-05-17 13 25 14" src="https://cloud.githubusercontent.com/assets/12981964/26149809/691147b6-3b04-11e7-870b-5fad796bc913.png">

**Comment by oconnor663** [comment]
@m4xch3 yep, that error's intentional right now, and we'll remove it when the new proof flow is live. Still in Facebook review.

**Comment by oconnor663** [comment]
Ok, the fix is live. Please try it out and let me know if you run into problems.

**Comment by bobtiki** [comment]
Just worked for me.

**Comment by SamuelEnglard** [comment]
Worked for me too!

**Comment by niall-byrne** [comment]
Resolve for me as well, thanks for taking care of this.  Is this a bad time to suggest Linkedin?

**Comment by julesthebit** [comment]
Yes, working here too. Thanks guys.

**Comment by CTassisF** [comment]
My Facebook proof is still failing :( I've tried revoking and adding it again a few times already.
Keybase profile:https://keybase.io/ctf
Facebook proof: https://www.facebook.com/ctassisf/posts/10213150101210421

**Comment by oconnor663** [comment]
@CTassisF hmm, it looks correct at first glance. I notice that there's a one letter difference between the sig ID in your post and what I see when I manually base64 the sig ID from https://keybase.io/ctf/chain. Let me look into that..

**Comment by oconnor663** [comment]
Ok, the one letter difference is expected, I always forget that. (Has to do with a signature type byte that we append to the full ID.) `keybase id ctf` is working for me now and showing your Facebook proof -- let me figure out why the server disagrees...

**Comment by oconnor663** [comment]
@CTassisF yep, this was a new server bug. We weren't consistently handling the capital letters in your Keybase username. Fix is in review.

**Comment by oconnor663** [comment]
@CTassisF ok, you should be able to remake your proof now. Let me know how it goes.

**Comment by CTassisF** [comment]
Fixed :) Thanks!

**Comment by niall-byrne** [comment]
There seems to be a secondary issue here, the callback is now throwing a 500 error.

**Comment by techmagus** [comment]
Throwing: "Error 500. Something is not right. We will look into it." When posting.

Tried posting manually but it doesn't read the manual posting.

Could be that FB is filtering keybase.io or blocked altogether.

**Comment by maxtaco** [comment]
See our earlier announcement on Twitter and in a different GH issue, but FB has shitcanned our App, so we're now in a review/appeal process to reenable it.  Hopefully within 24 hours. Stay tuned!

**Comment by niall-byrne** [comment]
Thanks for pointing this out.

**Comment by niall-byrne** [comment]
I see that the secondary issue is resolved now.
@oconnor663 Thanks for resolving this, and @maxtaco thanks for disseminating the info with respect to facebook's approval process.

**Comment by tglaeser** [comment]
This still fails for me ...

https://keybase.io/tamglaeser
https://www.facebook.com/tullia.glaeser/posts/1922031968074002

Got the same HTTP 403 return code when creating the post on fb.

Please reopen. Thanks.

**Comment by niall-byrne** [comment]
@oconnor663 ^

**Comment by oconnor663** [comment]
Thanks for the tag, taking a look.

**Comment by oconnor663** [comment]
@tglaeser, here's what our server is got from Facebook when we tried to fetch your posts:

```
{
    "error": {
        "message": "An unknown error has occurred.",
        "type": "OAuthException",
        "code": 1,
        ...
    }
}
```

Any chance you did something interesting with the permissions you're granting the Keybase Facebook app?

**Comment by tglaeser** [comment]
Thanks for looking into this. Not that I'm aware of. Not sure what you mean by _Keybase Facebook app_, only trying to link the Facebook account to Keybase. I'm using Keybase via the browser as of now to ensure that I'm running the latest Keybase version.

The [post](https://www.facebook.com/tullia.glaeser/posts/1922031968074002) is public and returns HTTP code 200 ...
```
$ curl -I https://www.facebook.com/tullia.glaeser/posts/1922031968074002
HTTP/1.1 200 OK
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://www.facebook.com
Access-Control-Expose-Headers: X-FB-Debug, X-Loader-Length
Vary: Origin
Pragma: no-cache
public-key-pins-report-only: max-age=500; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="q4PO2G2cbkZhZ82+JgmRUyGMoAeozA+BSXVXQWB8XWQ="; report-uri="http://reports.fb.com/hpkp/"
access-control-allow-method: OPTIONS
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Strict-Transport-Security: max-age=15552000; preload
Cache-Control: private, no-cache, no-store, must-revalidate
Set-Cookie: fr=0pt4wgWvE5ufuPnrs..BZLh8T.99.AAA.0.0.BZLh8T.AWV2k2oF; expires=Tue, 29-Aug-2017 01:40:35 GMT; Max-Age=7776000; path=/; domain=.facebook.com; secure; httponly
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
X-FB-Debug: LVL86cmO0e222JUOOXiNXB5YjJ5WBBu02Kx96oHM0L14XTBs3iNORkwEaRK+QIvVtfIGPuVwWaUvtUXDPxyHow==
Date: Wed, 31 May 2017 01:40:35 GMT
Connection: keep-alive
```

**Comment by oconnor663** [comment]
Yeah, this is a little confusing. There is a "Keybase Facebook app", which is the Facebook entity to which you give permission to read your posts, and our servers act as that app when we read your post through the Graph API. The entire flow looks like this:

1. You make a proof in your Keybase client (the real one on your desktop, or the website), and we generate a link for you to click on.
2. The link takes you to a Facebook login dialog. There you give the "Keybase Facebook app" permission to read your posts.
3. The login dialog redirects back to a Keybase URL, which gives us an auth token for you, and then redirects again to a post dialog.
4. After posting (publicly! everybody remembers to make it public right?!), the post dialog redirects yet again to Keybase's servers, which signals us to fetch your new post ID through the Graph API and verify your proof.

In your case, it's the very last part of step 4 that's giving us trouble. We've been informed that you posted, and we're hitting the Graph API using the token we got from step 3. But instead of getting a list of your posts, we get that "unknown error". It's possible that the auth token is getting mangled somewhere in all the redirects (I notice in your case it's shorter than one I see generated for my test user, not sure if that's normal), though I think think random mangling usually results in a "failed to decrypt" error, so it's not a great theory.

**Comment by tglaeser** [comment]
I'm not convinced that it is _the very last part of step 4_. While the post shows up in fb, the post creation returns with the 403. So it seems that the public post, while created, is somehow invalid.

**Comment by niall-byrne** [comment]
@tglaeser Your issue seems to be an unrelated new issue to the problem @oconnor663 solved here, I want to suggest we close this ticket and open a new one specifically for this issue.

**Comment by tglaeser** [comment]
OK, created new ticket #2992.

**Comment by richards1052** [comment]
I'm getting a 500 error also on Facebook:

https://keybase.io/_/facebook_post_redirect?sig_id_med=ySEIB2W2bU95X-y1qo_TIy0Hw5rBtHxqQppwfmEAkcA&keybase_token=lgHZIGI4ZTg1MDI5NmRiYTM5ZWE3NGNhYWUwNDU1ZjIzNzE5zloMC9nOAAP0gMDEIF7N8Stbj1KXWiohBLChgEO07GBootbSxxNu5pC5M2BY#_=_

https://keybase.io/richards1052
https://www.facebook.com/richards1052/posts/10155674854077850

I've also posted a proof to Reddit & Keybase doesn't seem to find the proof.

https://www.reddit.com/r/KeybaseProofs/comments/7d3153/my_keybase_proof_redditrichards1052/?st=ja0uup3n&sh=16de4539
https://www.reddit.com/r/KeybaseProofs/comments/7d3153/my_keybase_proof_redditrichards1052/

**Comment by oconnor663** [comment]
@richards1052 it's a little hard to tell from our server logs, but it seems like when the server calls back to FB to look for the post you just made through their API, it doesn't see any posts at all. Is there any chance you tweaked the permissions we were given when you went through the FB auth flow?

**Comment by oconnor663** [comment]
For example, if you click "Edit This" here:

![image](https://user-images.githubusercontent.com/860932/32844982-a8cd7fba-c9f1-11e7-9b72-8d3bb9a5e5aa.png)

And then uncheck "Timeline Posts" here:

![image](https://user-images.githubusercontent.com/860932/32845014-ba8a8cd4-c9f1-11e7-83c0-63c2e008b049.png)

Then you can cause this error. One way to fix it would be to delete the Keybase app here and repeat the entire flow (or you can go in and manually tweak its permissions):

![image](https://user-images.githubusercontent.com/860932/32845091-e68d229c-c9f1-11e7-81a0-ffa16539c9cb.png)

**Comment by richards1052** [comment]
One weird thing that happened is that I made sure that the proof that was posted was set to public.  Then I posted it to Facebook (and I can see the post in my timeline) & it failed with the 500 error.  Then I went to my FB apps & saw Keybase listed.  When I looked at the settings it was set to private.  I changed it to Public and tried the proof again.  Again it published to the timeline, but I still got that 500 error.

So I think somehow there's something interfering with the settings & it may still think it's private even though it's public.  But that's only a guess.  I really have no idea what's going on.  I wonder if there's a global FB setting that I've configured for the apps to be private which I need to change?

So you think I should delete the Keybase app on FB & try over again?

**Comment by richards1052** [comment]
Hey, I just checked the account of someone else who's on Keybase & I do see the Keybase chat logo in his profile.  What does that mean?  Doesn't it mean everything worked?  Regardless of whether it's saying my proof failed?

Color me puzzled...

**Comment by oconnor663** [comment]
> Hey, I just checked the account of someone else who's on Keybase & I do see the Keybase chat logo in his profile.

I'm having trouble understanding what you mean by this part. Maybe you're talking about the Keybase browser extension? (Do you have that installed? It tends to create buttons in various places. That wouldn't have much to do with your proofs succeeding or failing, if so.)

**Comment by richards1052** [comment]
Yes, I have the browser extension installed and am doing this via my pc.  So if I send a msg via the extension it's sent to the other FB user successfully?

As for the other problem, I'm going to uninstall the Keybase app for FB, then repost to FB.  I'll take a screenshot of what I see in the settings before posting.  I believe the Timeline Posts was checked & greyed out the last time I tried to publish the proof.  But I'll make sure it's checked.

**Comment by richards1052** [comment]
Hey, I just uninstalled the app.  Then I retried the proof & instead of getting the 500 error, this time it worked! Whadaya know!  

When I uploaded the proof & it installed the app the first time, something must still have been wrong despite the fact that I could see the proof posted to my TL & could see the app in my list of apps.  I'm guessing it had something to do with the app being set to private.  Even though I changed the setting to public, something didn't take..

**Comment by oconnor663** [comment]
Interesting! Thanks for playing around with this for us. I'll file a ticket to take a look at that flow, and see if we can give people more helpful errors if they do the same thing.

**Comment by richards1052** [comment]
Yeah, I think the suggestion to uninstall the app on FB & start the proof process clean is a good start when you get such an error.

**Comment by Karunamon** [comment]
Just wanted to say that @oconnor663 's idea fixed this problem with a friend I was trying to get set up on Keybase. They're super privacy-conscious and disabled the "see your timeline posts" option (they regularly disable everything that isn't optional) on the authorization screen, since they thought that the post being public was all they needed.

Would it be a good suggestion to add a note to this effect to the same screen where you're told you must set your post public?
