### ISSUE TITLE
keybase.pub uses fa-globe for facebook

### ISSUE THREAD

**Issue by damongant** [keybase/keybase-issues#3093]
When viewing files from the KBFS on keybase.pub, facebook is displayed with fa-globe on the side. Because facebook shortnames allow dots and the proof is always right above other websites, there is a little bit of a social engineering vector here.

![](https://my.mixtape.moe/ybpgnm.png)

**Comment by w2ak** [comment]
Hello :)

I think it was solved (recently I guess). I see the Facebook icon next to your username, not the globe.

neze

**Comment by damongant** [comment]
Still showing fa-globe to me.

![](https://my.mixtape.moe/qfnnfe.png)

**Comment by w2ak** [comment]
Oh sorry I realize I must have misread your post and checked on the wrong page. At least it’s keeping the issue active ? :/

**Comment by junderw** [comment]
Still broken for me too.

**Comment by jrtapsell** [comment]
I can confirm that I am seeing the globe as well, while this is limited to linking to facebook only it still seems like an issue
