### ISSUE TITLE
macOS: hiding the app doesn't make the window disappear

### ISSUE THREAD

**Issue by aharpole** [keybase/keybase-issues#3388]
Steps to reproduce: 

1. Open the Keybase app.
2. Select the menu item Keybase > Hide Keybase (or use the keyboard shortcut ⌘H)

Expected results:
Keybase should hide

Actual results:
The previous open app comes into focus and Keybase's window stays visible behind it.

**Comment by aharpole** [comment]
![keybase-bug](https://user-images.githubusercontent.com/507570/55976025-14e93180-5c40-11e9-8081-2e6cbb2c18fc.gif)

**Comment by tylergaw** [comment]
🎊 Was having the same issue. Seems it's fixed as of yesterday 2019/07/11. Version:

![Screen Shot 2019-07-12 at 10 15 30 AM](https://user-images.githubusercontent.com/233859/61134672-1966f580-a48e-11e9-9f12-73ade7b51d0f.png)

**Comment by emilyaviva** [comment]
The issue is not fixed for me as of 10 Jan 2020. When I hit Command-H to hide, the window gets moved to the back of the stack on the desktop but it's still visible and I can click in it to refocus on it.
<img width="396" alt="Screen Shot 2020-01-10 at 2 53 50 PM" src="https://user-images.githubusercontent.com/12450261/72192059-1905d380-33b9-11ea-8894-db58e2e0e0c8.png">
